topics = {
    "DSA": [
        "Arrays",
        "Strings",
        "Linked List",
        "Stacks",
        "Queues",
        "Trees",
        "Binary Search Trees",
        "Graphs",
        "Sorting Algorithms",
        "Searching Algorithms",
        "Recursion & Backtracking",
        "Dynamic Programming",
        "Greedy Algorithms",
        "Hashing",
        "Time & Space Complexity",
    ],
    "DBMS": [
        "ER Model",
        "Normalization (1NF-BCNF)",
        "Keys (Primary/Foreign/Candidate)",
        "Joins",
        "Indexing",
        "Transactions",
        "ACID Properties",
        "Concurrency Control",
        "Deadlocks",
        "SQL vs NoSQL",
    ],
    "OS": [
        "Process vs Thread",
        "Process Scheduling Algorithms",
        "Memory Management",
        "Paging & Segmentation",
        "Virtual Memory",
        "Deadlocks",
        "Synchronization (Semaphores/Mutex)",
        "File Systems",
        "Inter-Process Communication",
    ],
    "Networking": [
        "OSI Model",
        "TCP/IP Model",
        "TCP vs UDP",
        "DNS",
        "HTTP vs HTTPS",
        "Routing & Switching",
        "Subnetting",
        "Firewalls",
        "Sockets",
    ],
    "OOPS": [
        "Classes & Objects",
        "Inheritance",
        "Polymorphism",
        "Encapsulation",
        "Abstraction",
        "Interfaces vs Abstract Classes",
        "Constructors",
        "Method Overloading vs Overriding",
    ],
    "SQL": [
        "Joins (Inner/Outer/Cross)",
        "Subqueries",
        "Aggregate Functions",
        "Group By & Having",
        "Indexes",
        "Views",
        "Stored Procedures",
        "Triggers",
        "Constraints",
    ],
    "Python": [
        "Data Types",
        "Functions & Lambda",
        "OOP in Python",
        "Decorators",
        "Generators & Iterators",
        "List/Dict Comprehensions",
        "Exception Handling",
        "Modules & Packages",
        "GIL",
    ],
    "Java": [
        "OOPs Concepts",
        "Collections Framework",
        "Exception Handling",
        "Multithreading",
        "JVM vs JRE vs JDK",
        "String Handling",
        "Generics",
    ],
}
